<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 *
 * @generated
 * @phutil-library-version 2
 */
phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' => array(
    'PhabricatorYubikeyAuthFactor' => 'extensions/auth/factor/PhabricatorYubikeyAuthFactor.php',
    'PhabricatorYubikeyConfigOptions' => 'extensions/config/option/PhabricatorYubikeyConfigOptions.php',
  ),
  'function' => array(),
  'xmap' => array(
    'PhabricatorYubikeyAuthFactor' => 'PhabricatorAuthFactor',
    'PhabricatorYubikeyConfigOptions' => 'PhabricatorApplicationConfigOptions',
  ),
));
